services:
  - type: web
    name: smart-recruitment-chatbot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn user_app:app -c gunicorn_config.py
    envVars:
      - fromDotEnv: true
